### ISSUE TITLE
Will not spawn

### ISSUE THREAD

**Issue by madgigabit** [FAXES/Area-of-Patrol#7]
Hello,

I am running into an issue with the AOP script as it will now spawn you in the AOP.

I enabled it in the config, and I tried typing the AOP name in lower case, and changing it to upper case.

It loads fine and what not but it will not spawn you at any of the coordinates given.

--[[
    5. AOP Spawn Locations
--]]

   AOPSpawnsEnabled = true
    AOPSpawns = {
        {
            AOPName = 'Sandy Shores',
            AOPCoords  = {x = 311.22, y = 3457.60, z = 36.15}
        },
        {
            AOPName = 'Paleto Bay',
            AOPCoords  = {x = -447.24, y = 5970.46, z = 31.78}
        },
        {
            AOPName = 'downtown',
            AOPCoords  = {x = 219.98, y = -913.38, z = 30.69}
        },
        {
            AOPName = 'rockford hills',
            AOPCoords  = {x = -851.57, y = -128.04, z = 37.62}
        },
    }

**Comment by FAXES** [comment]
This resource needs to be rewritten honestly. I'll one day find time to do this...
